name: Merge Branch and Test

on:
  push:
    branches:
      - main
      - QA
      - STAGE

jobs:
  merge-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.32.0 # optional, see action.yml for current default

      - name: Merge and Test
        run: |
          merge_and_test() {
            local target_branch=$1
            echo "Merging changes from main to $target_branch"
            git config --global user.email "ctobin@adobe.com"
            git config --global user.name "Collin Tobin"
            git fetch origin $target_branch
            git checkout $target_branch
            git merge --allow-unrelated-histories -s ours main
            git push origin $target_branch
          }

          merge_and_test QA
          merge_and_test STAGE
          merge_and_test PROD  # Change to your target prod branch

      - name: Check URL status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://example.com)
          if [ "$response" == "200" ]; then
            echo "URL is reachable with status code 200"
          else
            echo "URL is unreachable or returned a status code other than 200"
            exit 1
          fi
